include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    deprecated_member_use: ignore
    file_names: ignore
    library_private_types_in_public_api: ignore
    unused_field: ignore
    use_build_context_synchronously: ignore
