import 'package:flutter/material.dart';

final Map<String, Map<String, dynamic>> categories = const {
  'fun': {
    'name': 'Fun & Casual',
    'description': 'Lighthearted questions perfect for any group',
    'icon': Icons.sentiment_very_satisfied,
    'color': Colors.orange,
    'questions': [
      "Who's most likely to forget their keys?",
      "Who's most likely to become famous?",
      "Who's most likely to sleep through their alarm?",
      "Who's most likely to win the lottery and lose the ticket?",
      "Who's most likely to become a CEO?",
      "Who's most likely to move to another country?",
      "Who's most likely to adopt 5 pets?",
      "Who's most likely to appear on a reality TV show?",
      "Who's most likely to start their own business?",
      "Who's most likely to get lost using GPS?",
      "Who's most likely to accidentally send a text to the wrong person?",
      "Who's most likely to laugh at inappropriate moments?",
      "Who's most likely to forget an important event?",
      "Who's most likely to spend all their money on gadgets?",
      "Who's most likely to bring up a topic no one cares about?",
    ],
  },
  'adventures': {
    'name': 'Adventures & Travel',
    'description': 'For the thrill seekers and explorers',
    'icon': Icons.flight,
    'color': Colors.blue,
    'questions': [
      "Who's most likely to go skydiving?",
      "Who's most likely to travel without a plan?",
      "Who's most likely to live in another country?",
      "Who's most likely to climb a mountain?",
      "Who's most likely to swim with sharks?",
      "Who's most likely to take a spontaneous road trip?",
      "Who's most likely to go backpacking through Europe?",
      "Who's most likely to learn a new language for fun?",
      "Who's most likely to camp in the wilderness?",
      "Who's most likely to try an extreme sport?",
      "Who's most likely to go on a solo travel adventure?",
      "Who's most likely to move to a place they've never visited?",
      "Who's most likely to explore the deep sea?",
      "Who's most likely to become a travel blogger?",
      "Who's most likely to hike the longest trail in the world?",
    ],
  },
  'deep': {
    'name': 'Deep & Thoughtful',
    'description': 'More meaningful questions to spark conversation',
    'icon': Icons.psychology,
    'color': Colors.indigo,
    'questions': [
      "Who's most likely to change the world?",
      "Who's most likely to write a book about their life?",
      "Who's most likely to discover something important?",
      "Who's most likely to start a charity?",
      "Who's most likely to change careers completely?",
      "Who's most likely to follow their passion regardless of money?",
      "Who's most likely to make a sacrifice for someone else?",
      "Who's most likely to stand up for what they believe in?",
      "Who's most likely to find inner peace?",
      "Who's most likely to inspire others?",
      "Who's most likely to live without social media for a year?",
      "Who's most likely to have a hidden talent no one knows about?",
      "Who's most likely to forgive someone who doesn't deserve it?",
      "Who's most likely to pursue a cause they deeply care about?",
      "Who's most likely to never give up on their dreams?",
    ],
  },
  'silly': {
    'name': 'Silly & Random',
    'description': 'Ridiculous scenarios to make everyone laugh',
    'icon': Icons.mood,
    'color': Colors.pink,
    'questions': [
      "Who's most likely to trip on nothing?",
      "Who's most likely to laugh at the wrong moment?",
      "Who's most likely to wear mismatched socks?",
      "Who's most likely to talk to themselves?",
      "Who's most likely to dance in an elevator?",
      "Who's most likely to accidentally wear their clothes inside out?",
      "Who's most likely to get caught singing in the shower?",
      "Who's most likely to eat something that fell on the floor?",
      "Who's most likely to argue with a GPS?",
      "Who's most likely to text while walking and bump into something?",
      "Who's most likely to use silly voices when talking to animals?",
      "Who's most likely to take 50 selfies before posting one?",
      "Who's most likely to send a voice note instead of a text?",
      "Who's most likely to try to start a trend that never catches on?",
      "Who's most likely to wear pajamas to a party?",
    ],
  },
  'romance': {
    'name': 'Dating & Romance',
    'description': 'Questions about love, dating and relationships',
    'icon': Icons.favorite,
    'color': Colors.redAccent,
    'questions': [
      "Who's most likely to fall in love at first sight?",
      "Who's most likely to have a secret crush?",
      "Who's most likely to propose in public?",
      "Who's most likely to have the most interesting dating story?",
      "Who's most likely to date someone completely opposite to them?",
      "Who's most likely to flirt with a stranger?",
      "Who's most likely to have the most romantic date planned?",
      "Who's most likely to get back with their ex?",
      "Who's most likely to fall asleep during a date?",
      "Who's most likely to date someone their friends don't approve of?",
      "Who's most likely to believe in soulmates?",
      "Who's most likely to have a long-distance relationship?",
      "Who's most likely to have the most dramatic breakup?",
      "Who's most likely to send love letters?",
      "Who's most likely to get caught having a secret date?",
    ],
  },
  'dirty': {
    'name': 'Edgy & Scandalous',
    'description': 'For mature players only - more risqué questions',
    'icon': Icons.whatshot,
    'color': Colors.deepPurple,
    'questions': [
      "Who's most likely to get a risqué tattoo?",
      "Who's most likely to tell a scandalous secret?",
      "Who's most likely to streak in public?",
      "Who's most likely to have the wildest dating history?",
      "Who's most likely to have an outrageous guilty pleasure?",
      "Who's most likely to get caught doing something embarrassing?",
      "Who's most likely to have a secret admirer?",
      "Who's most likely to flirt with everyone in the room?",
      "Who's most likely to send a spicy text to the wrong person?",
      "Who's most likely to have an unusual fantasy?",
      "Who's most likely to be caught in a compromising position?",
      "Who's most likely to have the most provocative social media?",
      "Who's most likely to kiss someone in front of a crowd?",
      "Who's most likely to post a scandalous picture online?",
      "Who's most likely to start an affair?",
    ],
  },

  'fame': {
    'name': 'Fame & Celebs',
    'description': 'Spotlight moments and brushes with fame',
    'icon': Icons.star,
    'color': Colors.amber,
    'questions': [
      "Who's most likely to meet a celebrity and play it cool?",
      "Who's most likely to get a selfie with a famous person?",
      "Who's most likely to become a viral meme?",
      "Who's most likely to date a celebrity?",
      "Who's most likely to crash a VIP party?",
      "Who's most likely to be mistaken for a celebrity?",
      "Who's most likely to get interviewed on TV?",
      "Who's most likely to trend on social media?",
      "Who's most likely to star in a commercial?",
      "Who's most likely to have a celebrity feud?",
      "Who's most likely to have a famous doppelgänger?",
      "Who's most likely to appear on a podcast?",
      "Who's most likely to photobomb a celeb?",
      "Who's most likely to end up on TMZ?",
      "Who's most likely to win a meet-and-greet contest?",
    ],
  },

  'football': {
    'name': 'Football Fever',
    'description': 'For fans of the beautiful game',
    'icon': Icons.sports_soccer,
    'color': Colors.green,
    'questions': [
      "Who's most likely to cry after a match?",
      "Who's most likely to become a football coach?",
      "Who's most likely to argue about offside rules?",
      "Who's most likely to watch a full season without missing a match?",
      "Who's most likely to break a TV during a match?",
      "Who's most likely to get into a football debate online?",
      "Who's most likely to paint their face for a game?",
      "Who's most likely to travel for a World Cup?",
      "Who's most likely to skip work for a game?",
      "Who's most likely to name their child after a footballer?",
      "Who's most likely to fake an injury while playing?",
      "Who's most likely to own five football jerseys?",
      "Who's most likely to play football in the rain?",
      "Who's most likely to score an own goal?",
      "Who's most likely to dream of being a pro player?",
    ],
  },

  'astrology': {
    'name': 'Stars & Signs',
    'description': 'Celestial questions for zodiac lovers',
    'icon': Icons.nights_stay,
    'color': Colors.deepOrange,
    'questions': [
      "Who's most likely to ask someone's star sign on the first meeting?",
      "Who's most likely to blame Mercury retrograde?",
      "Who's most likely to read daily horoscopes?",
      "Who's most likely to date based on zodiac compatibility?",
      "Who's most likely to get a tarot reading?",
      "Who's most likely to believe in astrology 100%?",
      "Who's most likely to plan events based on moon phases?",
      "Who's most likely to use astrology as an excuse?",
      "Who's most likely to know everyone's sign?",
      "Who's most likely to have crystals in their room?",
      "Who's most likely to say 'that’s such a Scorpio thing'?",
      "Who's most likely to ask for your birth chart?",
      "Who's most likely to post astrology memes?",
      "Who's most likely to fall in love with an astrologer?",
      "Who's most likely to predict the future (wrongly)?",
    ],
  },

  'random': {
    'name': 'Wildcard WTF',
    'description': 'Unexpected, weird, and oddly specific',
    'icon': Icons.question_mark,
    'color': Colors.teal,
    'questions': [
      "Who's most likely to survive a zombie apocalypse?",
      "Who's most likely to become a cult leader?",
      "Who's most likely to be abducted by aliens?",
      "Who's most likely to fight a goose and lose?",
      "Who's most likely to accidentally time travel?",
      "Who's most likely to find a hidden treasure?",
      "Who's most likely to eat something just to see what it tastes like?",
      "Who's most likely to have a conspiracy theory blog?",
      "Who's most likely to challenge a ghost to a duel?",
      "Who's most likely to have a second secret life?",
      "Who's most likely to fall in love with an AI?",
      "Who's most likely to join a secret society?",
      "Who's most likely to have a bizarre superpower?",
      "Who's most likely to become a talking point in a documentary?",
      "Who's most likely to become friends with a raccoon?",
    ],
  },
  'wouldYouRather': {
    'name': 'Would You Rather',
    'description': 'Hard choices... with a twist: pick a player!',
    'icon': Icons.help_outline,
    'color': Colors.brown,
    'questions': [
      "Who’s most likely to eat something gross rather than do a dare?",
      "Who would you rather be stuck with on a desert island?",
      "Who would you rather have plan your wedding?",
      "Who would you rather prank call your ex?",
      "Who would you rather go on a spontaneous trip with?",
      "Who would you rather trust with your secrets?",
      "Who would you rather trade lives with for a week?",
      "Who would you rather be your lawyer in court?",
      "Who would you rather call to bail you out of jail?",
      "Who would you rather watch your pet while you're away?",
      "Who would you rather have give you a makeover?",
      "Who would you rather be your wingman/wingwoman?",
      "Who would you rather face in a dance battle?",
      "Who would you rather be your partner in a game show?",
      "Who would you rather switch parents with for a week?",
    ],
  },
  'jobs': {
    'name': 'Jobs & Ambitions',
    'description': 'Work, dreams, success... and weird career moments',
    'icon': Icons.work,
    'color': Colors.blueGrey,
    'questions': [
      "Who's most likely to become a billionaire?",
      "Who's most likely to quit their job in style?",
      "Who's most likely to fake a sick day?",
      "Who's most likely to get promoted next?",
      "Who's most likely to be their own boss?",
      "Who's most likely to turn a hobby into a career?",
      "Who's most likely to oversleep before an important meeting?",
      "Who's most likely to ace an interview with zero prep?",
      "Who's most likely to get fired for something dumb?",
      "Who's most likely to work 3 jobs at once?",
      "Who's most likely to start a successful business?",
      "Who's most likely to be the CEO of a big company?",
      "Who's most likely to go back to school for a new career?",
      "Who's most likely to love their 9-5?",
      "Who's most likely to dream big but procrastinate forever?",
    ],
  },

  'techGaming': {
    'name': 'Tech & Gaming',
    'description': 'For the nerds, gamers, and tech lovers of the group',
    'icon': Icons.videogame_asset,
    'color': Colors.indigo,
    'questions': [
      "Who's most likely to rage quit a game?",
      "Who's most likely to stay up all night gaming?",
      "Who's most likely to own every console?",
      "Who's most likely to build their own PC?",
      "Who's most likely to stream on Twitch?",
      "Who's most likely to code their own app?",
      "Who's most likely to fall for a tech scam?",
      "Who's most likely to wait in line for a new iPhone?",
      "Who's most likely to own VR gear?",
      "Who's most likely to play video games at work?",
      "Who's most likely to have the best gaming setup?",
      "Who's most likely to become a game developer?",
      "Who's most likely to argue about Android vs iPhone?",
      "Who's most likely to hack something just for fun?",
      "Who's most likely to rage over bad Wi-Fi?",
    ],
  },

  'familyDrama': {
    'name': 'Family Drama',
    'description': 'Relatable chaos, family secrets, and sibling wars',
    'icon': Icons.family_restroom,
    'color': Colors.deepOrange,
    'questions': [
      "Who's most likely to start drama at a family dinner?",
      "Who's most likely to be the favorite child?",
      "Who's most likely to cry at a family event?",
      "Who's most likely to spill a family secret?",
      "Who's most likely to fight with a sibling over food?",
      "Who's most likely to ghost a cousin group chat?",
      "Who's most likely to borrow money and not return it?",
      "Who's most likely to move out and never visit?",
      "Who's most likely to avoid family gatherings?",
      "Who's most likely to still be treated like a kid?",
      "Who's most likely to get caught gossiping?",
      "Who's most likely to cause chaos at a wedding?",
      "Who's most likely to be adopted (as a joke)?",
      "Who's most likely to win an argument with mom?",
      "Who's most likely to forget a relative's birthday?",
    ],
  },

  'school': {
    'name': 'School Days',
    'description': 'Memories, mishaps, and all things school-related',
    'icon': Icons.school,
    'color': Colors.purpleAccent,
    'questions': [
      "Who's most likely to forget their homework?",
      "Who's most likely to be late every morning?",
      "Who's most likely to have a crush on a teacher?",
      "Who's most likely to cheat and get caught?",
      "Who's most likely to be class clown?",
      "Who's most likely to fall asleep in class?",
      "Who's most likely to start a school rumor?",
      "Who's most likely to ace a test without studying?",
      "Who's most likely to skip school for no reason?",
      "Who's most likely to write on the bathroom walls?",
      "Who's most likely to be teacher’s pet?",
      "Who's most likely to be a hall monitor nobody respects?",
      "Who's most likely to organize a school protest?",
      "Who's most likely to break the vending machine?",
      "Who's most likely to be prom king/queen?",
    ],
  },

  'techAI': {
    'name': 'Tech & AI',
    'description': 'Future vibes, robot friends, and AI paranoia',
    'icon': Icons.memory,
    'color': Colors.lightBlueAccent,
    'questions': [
      "Who's most likely to fall in love with an AI?",
      "Who's most likely to argue with ChatGPT?",
      "Who's most likely to get replaced by a robot?",
      "Who's most likely to create their own AI?",
      "Who's most likely to fear AI taking over?",
      "Who's most likely to train an AI to do their job?",
      "Who's most likely to give AI too much info?",
      "Who's most likely to say 'AI can’t beat humans!'",
      "Who's most likely to befriend a chatbot?",
      "Who's most likely to think AI is already watching us?",
      "Who's most likely to teach AI sarcasm?",
      "Who's most likely to write a novel with AI help?",
      "Who's most likely to build a robot companion?",
      "Who's most likely to lose an argument to Siri?",
      "Who's most likely to automate their whole life?",
    ],
  },

  'music': {
    'name': 'Music & Vibes',
    'description': 'Tastes, talents, and tunes that define the group',
    'icon': Icons.music_note,
    'color': Colors.pinkAccent,
    'questions': [
      "Who's most likely to know every lyric ever?",
      "Who's most likely to DJ at a party?",
      "Who's most likely to cry over a sad song?",
      "Who's most likely to sing in the shower?",
      "Who's most likely to start a band?",
      "Who's most likely to go to every concert?",
      "Who's most likely to listen to weird music?",
      "Who's most likely to hate popular music?",
      "Who's most likely to judge your playlist?",
      "Who's most likely to blast music at 2AM?",
      "Who's most likely to have amazing taste in music?",
      "Who's most likely to karaoke with zero shame?",
      "Who's most likely to become a famous artist?",
      "Who's most likely to discover underground bands?",
      "Who's most likely to listen to one song on repeat all week?",
    ],
  },

  'foodies': {
    'name': 'Foodies Only',
    'description': 'Delicious debates and guilty cravings',
    'icon': Icons.fastfood,
    'color': Colors.deepPurpleAccent,
    'questions': [
      "Who's most likely to eat something off the floor?",
      "Who's most likely to be a food critic?",
      "Who's most likely to eat the weirdest thing?",
      "Who's most likely to cook the best meal?",
      "Who's most likely to burn water?",
      "Who's most likely to order dessert first?",
      "Who's most likely to cry if food is bad?",
      "Who's most likely to steal fries from your plate?",
      "Who's most likely to eat 5 meals a day?",
      "Who's most likely to post food pics online?",
      "Who's most likely to have weird food combos?",
      "Who's most likely to bring snacks everywhere?",
      "Who's most likely to eat the last slice without asking?",
      "Who's most likely to win a hot dog eating contest?",
      "Who's most likely to make a mess while eating?",
    ],
  },

  'nostalgia': {
    'name': 'Throwback / Nostalgia',
    'description': 'Childhood chaos, old school memories, and retro fun',
    'icon': Icons.history_edu,
    'color': Colors.orangeAccent,
    'questions': [
      "Who's most likely to miss the early 2000s?",
      "Who's most likely to cry over old cartoons?",
      "Who's most likely to still have their childhood toy?",
      "Who's most likely to remember everyone’s MSN username?",
      "Who's most likely to rewatch old shows?",
      "Who's most likely to own a flip phone if they could?",
      "Who's most likely to love cassette tapes or CDs?",
      "Who's most likely to play old video games forever?",
      "Who's most likely to start a sentence with ‘Back in my day…’?",
      "Who's most likely to still remember their school anthem?",
      "Who's most likely to call 90s cartoons ‘peak TV’?",
      "Who's most likely to sing an old commercial jingle?",
      "Who's most likely to keep printed photos everywhere?",
      "Who's most likely to hoard old magazines or toys?",
      "Who's most likely to throw a retro-themed party?",
    ],
  },
  'friendship': {
    'name': 'Friendship Vibes',
    'description': 'Loyalty, laughter, inside jokes, and messy moments',
    'icon': Icons.group,
    'color': Colors.tealAccent,
    'questions': [
      "Who's most likely to cancel plans last minute?",
      "Who's most likely to be the group therapist?",
      "Who's most likely to disappear for weeks then show up like nothing happened?",
      "Who's most likely to remember everyone's birthday?",
      "Who's most likely to never reply in the group chat?",
      "Who's most likely to make the best memes about the group?",
      "Who's most likely to keep a secret no matter what?",
      "Who's most likely to take a bullet for their best friend?",
      "Who's most likely to forget your name mid-story?",
      "Who's most likely to cry during a deep conversation?",
      "Who's most likely to start drama, then act innocent?",
      "Who's most likely to be brutally honest (in a good way)?",
      "Who's most likely to show up uninvited—but it's okay?",
      "Who's most likely to stay friends forever?",
      "Who's most likely to drop everything to help you?",
    ],
  },
  'wouldYouRather2': {
    'name': 'Would You Rather 2',
    'description': 'Even more impossible choices… choose a player!',
    'icon': Icons.shuffle,
    'color': Colors.teal,
    'questions': [
      "Who would you rather be stranded with in the mountains?",
      "Who would you rather let pick your next tattoo?",
      "Who would you rather be stuck in traffic with for 6 hours?",
      "Who would you rather have write a song about you?",
      "Who would you rather take to meet your parents?",
      "Who would you rather swap social media accounts with?",
      "Who would you rather have as your teammate in a zombie apocalypse?",
      "Who would you rather be your boss for a year?",
      "Who would you rather trust to deliver an important message?",
      "Who would you rather let choose your outfits for a week?",
      "Who would you rather be in a cooking competition with?",
      "Who would you rather confess a crush to on your behalf?",
      "Who would you rather be stuck in an escape room with?",
      "Who would you rather take fashion advice from?",
      "Who would you rather let plan your surprise birthday party?",
    ],
  },
  'test': {
    'name': 'test',
    'description': 'Even more impossible choices… choose a player!',
    'icon': Icons.shuffle,
    'color': Colors.teal,
    'questions': [
      "Who would you rather be stranded with in the mountains?",
      "Who would you rather let pick your next tattoo?",
    ],
  },
};
