// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATjibZcLK1eQKrXf2FNfQWd96U6XjCg1M',
    appId: '1:361948538536:web:77843ace366c741075c49d',
    messagingSenderId: '361948538536',
    projectId: 'who-s-most-likely-to-3f557',
    authDomain: 'who-s-most-likely-to-3f557.firebaseapp.com',
    databaseURL: 'https://who-s-most-likely-to-3f557-default-rtdb.firebaseio.com',
    storageBucket: 'who-s-most-likely-to-3f557.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBypHiZ86NLWpo8M9qp_3Re0mx1_aw8Irg',
    appId: '1:361948538536:android:e5111f4270b82b7475c49d',
    messagingSenderId: '361948538536',
    projectId: 'who-s-most-likely-to-3f557',
    databaseURL: 'https://who-s-most-likely-to-3f557-default-rtdb.firebaseio.com',
    storageBucket: 'who-s-most-likely-to-3f557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWs9PYSE1ydLIumGQoHbcTM9pwOjngeXI',
    appId: '1:361948538536:ios:e718eb0353f5087075c49d',
    messagingSenderId: '361948538536',
    projectId: 'who-s-most-likely-to-3f557',
    databaseURL: 'https://who-s-most-likely-to-3f557-default-rtdb.firebaseio.com',
    storageBucket: 'who-s-most-likely-to-3f557.firebasestorage.app',
    iosClientId: '361948538536-2sur1hoqgbek04sn1ioj3g67sd3f7hrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.whoMostLikelyTo',
  );
}
