// ignore_for_file: deprecated_member_use, use_build_context_synchronously, library_private_types_in_public_api

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is the file generated by flutterfire CLI
import 'package:who_most_likely_to/screens/HomeScreen.dart';
import 'package:provider/provider.dart';
import 'package:who_most_likely_to/providers/theme_provider.dart';
import 'package:who_most_likely_to/services/sound_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Required for async in main
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await SoundService().initialize(); // Initialize sound service
  runApp(
    ChangeNotifierProvider(
      create: (_) => ThemeProvider(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);

    return MaterialApp(
      title: 'Who\'s Most Likely To',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.purple,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        brightness: Brightness.light,
      ),
      darkTheme: ThemeData(
        primarySwatch: Colors.purple,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        brightness: Brightness.dark,
      ),
      themeMode: themeProvider.isDarkMode ? ThemeMode.dark : ThemeMode.light,
      home: const HomeScreen(),
    );
  }
}
